# Generated by Django 5.1.1 on 2024-09-10 19:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='00:00', max_length=50),
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_id',
            new_name='youtube_id',
        ),
    ]
