# Generated by Django 5.1.1 on 2024-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
