# Generated by Django 5.1.1 on 2024-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
