# Generated by Django 5.1 on 2024-08-20 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_start',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
