# Generated by Django 5.1.1 on 2024-09-06 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_created_at_alter_user_session_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
