# Generated by Django 5.1 on 2024-08-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_general', models.BooleanField()),
                ('is_table_specific', models.BooleanField()),
                ('songs', models.ManyToManyField(to='song.song')),
                ('table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.table')),
            ],
        ),
    ]
