# Generated by Django 5.1.1 on 2024-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
