# Generated by Django 5.1.1 on 2024-09-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='table_id',
            new_name='table',
        ),
    ]
