# Generated by Django 5.1.1 on 2024-09-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_playlistsong_playlist_songs'),
        ('user', '0003_alter_user_created_at_alter_user_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='play',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
