# Generated by Django 5.1.1 on 2024-09-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='password',
        ),
        migrations.AddField(
            model_name='administrator',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
