# Generated by Django 5.1.1 on 2024-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_administrator_user_alter_administrator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
