# Generated by Django 5.1.1 on 2024-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_empresa_alter_table_max_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
